["batpy"]
"BatPaC version" = "BatPaC 5.0 2022-07-22"
"BatPaC SemVer" = "0.0.0"

["Dashboard"]
"Restart (0/1)" = "D6"
# Chemistry
## Positive Electrode
"Electrode Couple" = "E13"
"Positive active material specific capacity, mAh/g" = "E15"
"Void volume fraction, % of positive electrode" = "E16"
"Positive foil thickness, mm" = "E17"
"Maximum positive electrode thickness, µm" = "E18"

## Negative Electrode
"Negative active material specific capacity, mAh/g" = "E21"
"N/P capacity ratio after formation" = "E22"
"Void volume fraction, % of negative electrode" = "E23"
"Negative current collector thickness, µm" = "E24"

"Separator thickness, µm" = "E26"

# Battery Design
## General
"Vehicle Type" = "E33"
"Calculate Charging Requirements?" = "E34"
"OEM Upper Cuttoff SOC" = "J32"
"OEM Lower Cutoff SOC" = "J33"


## Power and Storage Requirements
"Use default power requirements for vehicle" = "D40"
## Material Costs
"Al foil, $/m²" = "E97"
"Cu foil, $/m²" = "E98"
"Separator, $/m²" = "E99"
"Electrolyte, $/L" = "E100"

## Plant Specifications
"Method to calculate plant utilization" = "D107"
"Cell yield, % of built cells that pass inspection" = "D112"
## Pack Manufacturing Method and Cost Options
"Method for manufacturing pack" = "D116"
"Option for pack cost" = "D118"

# Summary of Results and Graphing
"Unit" = "C145"
"X =" = "C146"
"Y1 =" = "C147"
"Y2 =" = "C148"

# Manufacturing and Costs
## Material Costs
"Positive Electrode, $/kg, Active material, $/kg" = "E86"
"Positive Electrode, $/kg, Carbon additive, $/kg" = "E87"
"Positive Electrode, $/kg, Binder, $/kg" = "E88"
"Positive Electrode, $/kg, Solvent (NMP), $/kg" = "E89"

# Negative electrode, $/kg
"Negative electrode, $/kg, Active material, $/kg" = "E92"
"Negative electrode, $/kg, Carbon additive, $/kg" = "E93"
"Negative electrode, $/kg, Binder, $/kg" = "E94"
"Negative electrode, $/kg, Solvent (Water), $/kg" = "E95"

["Dashboard"."Battery 1"]
## Calculation and Validation
"Configuration Errors (see table to right)" = "D129"
"Configuration Warnings (see table  to right)" = "D130"
"Plant Size, GWh" = "D131"
"Power-to-energy ratio" = "D132"
"Adequacy of cooling" = "D133"
"Cathode thickness limited by" = "D134"

["Dashboard"."Battery 2"]
## Calculation and Validation
"Configuration Errors (see table to right)" = "E129"
"Configuration Warnings (see table  to right)" = "E130"
"Plant Size, GWh" = "E131"
"Power-to-energy ratio" = "E132"
"Adequacy of cooling" = "E133"
"Cathode thickness limited by" = "E134"

["Dashboard"."Battery 3"]
## Calculation and Validation
"Configuration Errors (see table to right)" = "F129"
"Configuration Warnings (see table  to right)" = "F130"
"Plant Size, GWh" = "F131"
"Power-to-energy ratio" = "F132"
"Adequacy of cooling" = "F133"
"Cathode thickness limited by" = "F134"

["Dashboard"."Battery 4"]
## Calculation and Validation
"Configuration Errors (see table to right)" = "G129"
"Configuration Warnings (see table  to right)" = "G130"
"Plant Size, GWh" = "G131"
"Power-to-energy ratio" = "G132"
"Adequacy of cooling" = "G133"
"Cathode thickness limited by" = "G134"

["Dashboard"."Battery 5"]
## Calculation and Validation
"Configuration Errors (see table to right)" = "H129"
"Configuration Warnings (see table  to right)" = "H130"
"Plant Size, GWh" = "H131"
"Power-to-energy ratio" = "H132"
"Adequacy of cooling" = "H133"
"Cathode thickness limited by" = "H134"

["Dashboard"."Battery 6"]
## Calculation and Validation
"Configuration Errors (see table to right)" = "I129"
"Configuration Warnings (see table  to right)" = "I130"
"Plant Size, GWh" = "I131"
"Power-to-energy ratio" = "I132"
"Adequacy of cooling" = "I133"
"Cathode thickness limited by" = "I134"

["Dashboard"."Battery 7"]
## Calculation and Validation
"Configuration Errors (see table to right)" = "J129"
"Configuration Warnings (see table  to right)" = "J130"
"Plant Size, GWh" = "J131"
"Power-to-energy ratio" = "J132"
"Adequacy of cooling" = "J133"
"Cathode thickness limited by" = "J134"
